### ISSUE TITLE
Question: How to configure GraphQL in Besu setup?

### ISSUE THREAD

**Issue by iskdrews** [ConsenSys/quorum-dev-quickstart#116]
Hi, 
I need help on how to configure and setup the GraphQL plugin in Besu setup by running the `./run.sh` command. 
Do I need to add more config for GraphQL in the `docker-compose.yml`? or that should be in the `list.sh` script? 
In the end Im looking forward to have this GraphQL link working: 
- `http://${HOST}:8547/graphql`

**Comment by antonydenyer** [comment]
Looks like the port isn't exposed. If you expose 8457 on the `rpcnode` that should do the trick.

**Comment by joshuafernandes** [comment]
Hi @iskdrews the `list.sh` just lists the services running, @antonydenyer is right you need to : 
- expose port 8547 https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/templates/besu/docker-compose.yml#L487 
- enable the graphql options https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/templates/besu/docker-compose.yml#L49  Docs for graphql https://besu.hyperledger.org/en/latest/Reference/CLI/CLI-Syntax/#graphql-http-cors-origins

**Comment by iskdrews** [comment]
Thanks so much @antonydenyer and @joshuafernandes
