### ISSUE TITLE
Azure Marketplace Dev Test services url link is wrong

### ISSUE THREAD

**Issue by leestott** [ConsenSys/quorum-dev-quickstart#119]
The current Azure Marketplace image for 
Quorum Dev Quickstart needs updating the GitHub link goes to https://github.com/ConsenSys/besu-sample-networks/blob/master/besu_ibft2/genesis.json.template - THIS IS NO LONGER VALID
 
 Can the url be updated to go to this new repo https://github.com/ConsenSys/quorum-dev-quickstart
 
 Azure Marketplace Image
![MarplQuor](https://user-images.githubusercontent.com/2511341/142612449-f0d30e31-fdfb-459a-b2ba-beec4b656e4c.png)
?

**Comment by joshuafernandes** [comment]
Hi @leestott thanks for this. I've updated things in the offering but it'll take a couple of weeks passing Azure's marketplace checks to come live
