### ISSUE TITLE
QuickStart Blockscout

### ISSUE THREAD

**Issue by Finmetrica** [ConsenSys/quorum-dev-quickstart#122]
I receive this message when i try to run ./run-blockscout.sh  

Network already in use (.quorumDevQuickstart.lock present).
Restart with ./resume.sh or remove with ./remove.sh before running again.

I installed an empty VM with Ubuntu 20. The server just contains quorum-dev-quickstaret.

whats is wrong?
Thanks

**Comment by joshuafernandes** [comment]
Hi @Finmetrica , thankyou for reporting this. Could you try with version 0.0.45 or upwards please? I've updated it so blockscout is now part of the main questions and not a seperate script. Docs have PR's and will be updated when approved and merged. 

Give us a yell if you have further issues
