### ISSUE TITLE
Making Cakeshop optional

### ISSUE THREAD

**Issue by isavelli** [ConsenSys/quorum-dev-quickstart#135]
Hello,

I noticed that in v0.0.49 Cakeshop has been removed. For me this tool was very useful, could it be possible to have it as an optional software instead of completely removing it?

**Comment by joshuafernandes** [comment]
Hi @isavelli thank you for raising this. Could you elaborate on what features you were specifically using in Cakeshop? 

We are in the process of standardising the tooling used in the quickstart so that it supports both clients

**Comment by isavelli** [comment]
Hi @joshuafernandes, for example in Cakeshop I can compile and deploy contract with privareFor, then I can explore the block deployed, change node, everything with one tool

**Comment by joshuafernandes** [comment]
Hi @isavelli Thanks for that feedback. We are looking at alternatives re the private txns and a GUI tool there. There are quite a few concerns and antipatterns in cakeshop at present and we would like to address those and standardize things going forward. I will discuss the request and see what the consensus is re bringing it back - in the meantime though you can deploy cakeshop as a standaone component and continue with testing

**Comment by joshuafernandes** [comment]
Hi @isavelli We are likely developing a new tool with a GUI for private transactions, which will support both clients. In the interim you can start cakeshop with the quorum-dev-quickstart following instructions here https://github.com/ConsenSys/cakeshop#running-with-the-quorum-dev-quickstart
