### ISSUE TITLE
wget not found in hyperledger/besu:21.10.2

### ISSUE THREAD

**Issue by gomezgoiri** [ConsenSys/quorum-dev-quickstart#138]
After creating a sample network I see in the _docker-compose.yml_ that _x-besu-tx-def_ checks whether tessera is running before starting besu (see it [here](
https://github.com/ConsenSys/quorum-dev-quickstart/blob/f31ba1055f13bea6584174d23c83df2cc0990820/templates/besu/docker-compose.yml#L66)).

However, the services which import this template (member1besu, member2besu and member3besu) redefine the _entrypoint_ ignoring that check. Wouldn't it be clearer to include the actual entrypoint in _x-besu-tx-def_ and define only the bits that change in the mentioned services?

When I did this (reusing the same entrypoint defined in the template and using some variables in the services to define things like the actual _privacy-url_), I realized that __wget does not exist in the besu image__ (the version it uses is the _21.10.2_) so that check would not work even if the entrypoint defined in the template was actually called.

The network I create to see this behavior is the following one:

```bash
npx quorum-dev-quickstart@latest --clientType besu \
  --orchestrate false \
  --quorumKeyManager false \
  --privacy true \
  --monitoring none \
  --blockscout false \
  --outputPath ./
```

**Comment by joshuafernandes** [comment]
Hi @gomezgoiri good point and has been addressed by #140
