### ISSUE TITLE
Blockscout always indexing

### ISSUE THREAD

**Issue by kth-tw** [ConsenSys/quorum-dev-quickstart#159]
I try to create a quorum test network with below argument: 
```
- Which Ethereum client would you like to run? 2. GoQuorum
- Do you want to try out Codefi Orchestrate? N
- Do you want to try out Quorum Key Manager? N
- Do you wish to enable support for private transactions? Y
- Do you wish to enable support for logging with Splunk or ELK (Elasticsearch, Logstash & Kibana)? 3. ELK
- Do you wish to enable support for monitoring your network with Blockscout? Y
- Where should we create the config files for this network? Please choose either an empty directory, or a path to a new directory that does not yet exist. ./quorum-test-network
```

After run `run.sh`, the network start successfully.
When I create a transaction with `smart_contracts/script/public_tx.js`.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/88102592/160767788-11c47e13-8cd1-422e-944d-0cac0b12a293.png">
The transaction can be found in Ethereum Lite Explorer
<img width="528" alt="image" src="https://user-images.githubusercontent.com/88102592/160767989-87e34fe2-0f04-456f-b111-4da4bc163e87.png">
But in blockscout, it show `Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate.` in index.
<img width="1419" alt="截圖 2022-03-30 下午2 44 19" src="https://user-images.githubusercontent.com/88102592/160768397-8bbe0160-fefc-46ff-8c3d-c0a7e41d6dc0.png">
I got the block number of transaction is `217` from Lite Explorer. The blockscout show that block is `Block Mined, awaiting import...`
![image](https://user-images.githubusercontent.com/88102592/160768844-a96262fa-8b87-4e56-a4be-51fea9ee2d16.png)
And the transaction is in `Pending transaction`
<img width="992" alt="image" src="https://user-images.githubusercontent.com/88102592/160768958-5c94df67-43a5-47b5-8231-57a26c89f845.png">

**Comment by joshuafernandes** [comment]
Hi @kth-tw this needs to be raised with the team at Blockscout - we do not maintainers of Blockscout. I'd suggest checking the logs for blockscout and raising an issue there

**Comment by kth-tw** [comment]
It seem to be fixed in this PR https://github.com/blockscout/blockscout/pull/5302
And you use docker image which is owner by consensys
https://github.com/ConsenSys/quorum-dev-quickstart/blob/2d622ab309a09e6f13a3521ff5476e28adc4f629/templates/goquorum/docker-compose.yml#L121
Could you update the docker image?

**Comment by joshuafernandes** [comment]
Hi @kth-tw the issue has been merged recently, however there hasn't been a release with the issue https://github.com/blockscout/blockscout/releases. When there is a release we will update the image

**Comment by kth-tw** [comment]
I build a [docker image](https://hub.docker.com/layers/blockscout/eugene9467/blockscout/v4.0.0-goquorum/images/sha256-ec2d71906c1e2978fac68beed2e3b16f74b160478b559e0b3faba1088862a34b) which is base on 4.0.0 and [the change](https://github.com/blockscout/blockscout/pull/5302/files#diff-eaa58dcb9d2459f1a90a467ad3a0efef31b2c8a870dd97814afcb7ecabaea8cc)

Could you push this docker image to your docker hub repository, and replace tag in docker-compose.yml ?
