### ISSUE TITLE
npm run register-chain do not respond (GoQuorum setup)

### ISSUE THREAD

**Issue by malaoui79** [ConsenSys/quorum-dev-quickstart#16]
- ENV : MAC CATALINA
- node : v14.10.1
All the quorum-test-network component are up and running.
We have an issue on the deps_eth_client_1. It's in restarting mode and here is the log : 

*******************************************************************************
INFO [10-02|12:05:28.934] Maximum peer count ETH=50 LES=0 total=50

INFO [10-02|12:05:28.934] Smartcard socket not found, disabling err="stat /run/pcscd/pcscd.comm: no such file or directory"

ERROR[10-02|12:05:28.961] Failed to enumerate USB devices hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"

ERROR[10-02|12:05:28.961] Failed to enumerate USB devices hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"

ERROR[10-02|12:05:28.962] Failed to enumerate USB devices hub=trezor vendor=4617 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"

ERROR[10-02|12:05:28.962] Failed to enumerate USB devices hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"

ERROR[10-02|12:05:28.963] Failed to enumerate USB devices hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"

ERROR[10-02|12:05:28.964] Failed to enumerate USB devices hub=trezor vendor=4617 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"

INFO [10-02|12:05:28.964] Allocated cache and file handles database=/nodeData/geth/chaindata cache=16.00MiB handles=16

INFO [10-02|12:05:28.978] Persisted trie from memory database nodes=14 size=2.28KiB time=221.932µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B

INFO [10-02|12:05:28.980] Successfully wrote genesis state database=chaindata hash=eca552…e41c48

INFO [10-02|12:05:28.980] Allocated cache and file handles database=/nodeData/geth/lightchaindata cache=16.00MiB handles=16

INFO [10-02|12:05:28.994] Persisted trie from memory database nodes=14 size=2.28KiB time=37.557µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B

INFO [10-02|12:05:28.995] Successfully wrote genesis state database=lightchaindata hash=eca552…e41c48

the PRIVATE_CONFIG environment variable must be specified for Quorum
*******************************************************************************

npm run register-chain   do not respond.

Thanks for your help.

**Comment by joshuafernandes** [comment]
@malaoui79 apologies for the late reply, Could you please confirm if this is still an issue - am not able to reproduce this on my machine

**Comment by malaoui79** [comment]
Hi @joshuafernandes , thanks. I didn't try ...You can close it...I'l create a new ticket if I encounter the prob when I will have time to do the setup. Thanks.

**Comment by joshuafernandes** [comment]
Sounds good @malaoui79
