### ISSUE TITLE
http://localhost:8545 Unable to connect

### ISSUE THREAD

**Issue by oooomoooo** [ConsenSys/quorum-dev-quickstart#173]
The ubuntu system， I use has turned off the firewall, but I still can't link localhost: 8545, or the link is reset.
I did the following:
https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/using-the-quickstart/

Please help me！

**Comment by joshuafernandes** [comment]
Hello @oooomoooo Can you please post steps to reproduce and what options you selected? When you have your setup running can you post the output of `docker ps` please

**Comment by logicalfarhad** [comment]
Hi there, I am facing the same issue. I am using the ubuntu 20.04 version. After running the docker command from here [quorum-dev-quickstart](https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/using-the-quickstart/) I am trying to test the RPC node. However, I could not see any output. Here is the docker ps command output. As you can see, no port is assigned to the RPC
![Screenshot from 2022-07-26 18-37-28](https://user-images.githubusercontent.com/2293175/181062864-715efdda-1267-4021-a09c-5ef1fece6593.png)
 node. Other nodes are running fine.  
 
Any idea what's going on? Thanks in advance!

**Comment by joshuafernandes** [comment]
Hello @logicalfarhad could you please give us a list of steps to reproduce what you're seeing with specs of machine as well as version of the quickstart. Also what are the logs form any of the validators or rpcnode - it appears that none of them are working in the screenshot and are restarting?

**Comment by logicalfarhad** [comment]
Hello @joshuafernandes, I have followed the instruction from this link https://github.com/ConsenSys/quorum-dev-quickstart 
I did not see any log for quorum or validators, or RPC node. I only found logs for teserra. I am missing something to find out the logs? 
![image](https://user-images.githubusercontent.com/2293175/181191010-c681f694-3b8d-4576-802e-04fe08927b3f.png)

Thanks

**Comment by joshuafernandes** [comment]
Hi @logicalfarhad yep, thats correct. None of your goquorum containers have started. Run a `docker ps -a ` and then `docker logs -f quourm.......` to see why they have failed. Which version of the quickstart are you using that you see this behaviour on?

**Comment by joshuafernandes** [comment]
On v 0.0.73 (latest) I am unable to reproduce this. I have Ubuntu 22.04 and ran this with `npx quorum-dev-quickstart@0.0.73`

![image](https://user-images.githubusercontent.com/3722503/181386162-2493b3c4-fad1-42a7-a49d-595d8db0c494.png)

**Comment by logicalfarhad** [comment]
@joshuafernandes Unfortunately, it does not run on my pc. I will try with another PC.

**Comment by ianao3** [comment]
I also encountered this issue
https://github.com/ConsenSys/quorum-dev-quickstart/issues/211#issuecomment-1333378815
