### ISSUE TITLE
Link on GoQuorum README is broken

### ISSUE THREAD

**Issue by rodion-lim-partior** [ConsenSys/quorum-dev-quickstart#201]
Hi, the link on your GoQuorum README is broken. https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/goquorum/README.md

**Comment by joshuafernandes** [comment]
Hi @rodion-lim-partior the readme here in the repo is intentional, its meant to be viewed when run from `npm quorum-dev-quickstart` which puts the readme in the right path when the templating is done

**Comment by rodion-lim-partior** [comment]
Hey @joshuafernandes, I didn't mean the path is broken. Your link to official docs is showing a 404 error. It should be without getting-started.

**Comment by joshuafernandes** [comment]
Gotcha, thankyou @rodion-lim-partior this is fixed now in v 0.0.77
