### ISSUE TITLE
Transactions stuck in queue on rpcnode

### ISSUE THREAD

**Issue by wildsheepz** [ConsenSys/quorum-dev-quickstart#209]
Hi, I am new to quorum and I'm trying to deploy the simplestorage contract in Quorum Explorer. However, it seems that after clicking on the deploy button, the transaction seems to never complete. In the Nodes tab, I can see there is 1 Queued transaction on the rpcnode but it doesn't seem to be processed even after waiting a long time. I checked the logs and I saw recurring errors:

```
INFO [09-19|13:56:36.007] QBFT: initialize new round               address=0xDF8b560be949C229C821731554C33EAD5E3888A4 current.round=0 current.sequence=9 target.round=0 lastProposal.number=9 lastProposal.hash="85383d…4c5cac"
INFO [09-19|13:56:36.007] Commit new mining work                   number=10 sealhash="5e210d…e6e055" uncles=0 txs=0 gas=0 fees=0 elapsed="138.504µs"
WARN [09-19|13:56:36.007] Block sealing failed                     err=unauthorized
WARN [09-19|13:57:14.432] Served eth_hashrate                      conn=172.16.239.44:55602 reqid=148 t="4.402µs"  err="the method eth_hashrate does not exist/is not available"
```
Is the error related? How do I get transactions to work? I can't seem to send eth from genesis accounts to my wallet either.

**Comment by joshuafernandes** [comment]
Hello @wildsheepz 
Thanks for submitting this, could you please give us the following so we can look into this further?
- the version that you are running
- steps to reproduce this issue
- do you see blocks being created ie the chain head progressing?
- 
Cheers

**Comment by wildsheepz** [comment]
I checked out master so its #206.
All I did was `npm start`, then browse to http://127.0.0.1:26000, connected metamask and tried to deploy a contract. 

Anyway, I may have found the problem. The private key for rpcnode in "network/smart_contracts/permissioning/scripts/keys.js" is wrong. 

```
    validator4: {
      name: "validator1",
      url: "http://127.0.0.1:21004",
      nodekey: "8f6ae009cdbbf6e6fa739b91a4483f251bbe89f6570d34856554533b36c93c55",
      accountAddress: "0xf48de4a0c2939e62891f3c6aca68982975477e45",
      accountPrivateKey: "0x7f012b2a11fc651c9a73ac13f0a298d89186c23c2c9a0e83206ad6e274ba3fc7"
    },        
    rpcnode: {
      name: "rpcnode",
      url: "http://127.0.0.1:8545",
      wsUrl: "ws://127.0.0.1:8546",
      nodekey: "0e93a540518eeb673d94fb496b746008ab56605463cb9212493997f5755124d1",
      accountAddress: "0xc9c913c8c3c1cd416d80a0abf475db2062f161f6",
      accountPrivateKey: "0x7f012b2a11fc651c9a73ac13f0a298d89186c23c2c9a0e83206ad6e274ba3fc7" <--- its the same as validator4
    },       
```
After correcting it and starting again, the txns are going through now.

**Comment by joshuafernandes** [comment]
Gotcha, thanks for that @wildsheepz we'll fix that key
