### ISSUE TITLE
"Waiting for network to be up............"

### ISSUE THREAD

**Issue by trilloc** [ConsenSys/quorum-dev-quickstart#211]
![image](https://user-images.githubusercontent.com/63382707/191702125-d3919e4b-5418-4922-ad58-4fbf9beb8ab2.png)

on ubuntu 20.04, 4cvpu, 16G RAM, GCP -- after installing node, npm, docker-io, docker-compose and docker compose plugin,

I just ran the command:

npx quorum-dev-quickstart --clientType besu --outputPath ./quorum-test-network --monitoring default --privacy false --orchestrate true --quorumKeyManager false

It is stuck at "Waiting for network to be up...." This is for the 5th time or so.. Once I waited for more than an hour for it to finish, but it kept going...

((hyperledger/besu:22.7.1 seems to be continuously restarting... ))

Please help.

Thanks and Regards
Rajesh

TOP:
![image](https://user-images.githubusercontent.com/63382707/191703504-89c90d86-da8f-4cfe-afed-ac034ecee2d8.png)

DOCKER IMAGES:
![image](https://user-images.githubusercontent.com/63382707/191703600-bca3ad38-11bd-44f8-9c0b-5798f19e7a0d.png)

DOCKER PS:
![image](https://user-images.githubusercontent.com/63382707/191703744-f8b34ad9-2bca-473e-b822-e6f0380236f8.png)

**Comment by trilloc** [comment]
SOLVED: This is a problem with the user id being 1001 by default on GCP ubuntu. Logging in as user with id 1000 solves the problem.

**Comment by ianao3** [comment]
> SOLVED: This is a problem with the user id being 1001 by default on GCP ubuntu. Logging in as user with id 1000 solves the problem.

error:
![image](https://user-images.githubusercontent.com/58729233/205000393-1318772d-f28e-4c4e-ada5-ea122337e6ca.png)

my user:
![image](https://user-images.githubusercontent.com/58729233/204999697-7c380640-ec78-4d58-95d9-6002f188a3da.png)

my container
![image](https://user-images.githubusercontent.com/58729233/205000126-261846a7-2c43-4f56-9a97-6315a8904a45.png)

I try so many solutions, but all failed

**Comment by KonstantinosSekaras** [comment]
It's been a long time, and it might not be the same case, but as was mentioned by @AwaludinAR below, simply going for "usermod" to change the uid might not solve the issue, you probably need to to add the field user: root in the docker-compose file.

(https://github.com/hyperledger/besu/issues/4292#issuecomment-2209060861)
