### ISSUE TITLE
Stuck at 9 blocks

### ISSUE THREAD

**Issue by cyborgdennett** [ConsenSys/quorum-dev-quickstart#212]
Hello, I am running this with GoQuorum, and I get stuck at 9 blocks. I did nothing but do ./run.sh
![image](https://user-images.githubusercontent.com/40475862/200611421-1aea07fe-91ee-4478-8a23-3132a7f40b94.png)

**Comment by joshuafernandes** [comment]
Hello @cyborgdennett are your containers still running? That looks like one or more validators have failed, hence no more blocks

You can check with 
```docker ps```

**Comment by joshuafernandes** [comment]
Hi @cyborgdennett this is fixed in 0.0.80

Run `npx quorum-dev-quickstart@0.0.80` and you should be sorted

Cheers
