### ISSUE TITLE
UNC paths are not supported.  Defaulting to Windows directory.

### ISSUE THREAD

**Issue by jmcounters** [ConsenSys/quorum-dev-quickstart#213]
Running into this issue when running `npx quorum-dev-quickstart`

![image](https://user-images.githubusercontent.com/118317606/202046033-a9a4f9d6-9bd3-4a89-811f-d5508929c685.png)

![image](https://user-images.githubusercontent.com/118317606/202046133-656810d2-d86d-410b-aeaf-87e7ca7218c9.png)

![image](https://user-images.githubusercontent.com/118317606/202046159-b3030d32-f105-4308-9974-e39208d020c2.png)

**Comment by joshuafernandes** [comment]
Hello @jmcounters You need WSL for this to work. To the best of my knowledge this doesn;t work natively on Windows.
