### ISSUE TITLE
Web block explorer

### ISSUE THREAD

**Issue by jmcounters** [ConsenSys/quorum-dev-quickstart#217]
Hi!

Node info is not populating:

![image](https://user-images.githubusercontent.com/118317606/202897717-b91c120d-b085-4c59-aed3-570c680160b0.png)

**Comment by jmcounters** [comment]
Containers restarting often, most likely related. Can someone help?

![image](https://user-images.githubusercontent.com/118317606/202898776-cf16c358-33a5-4f96-829b-c5affb8200ac.png)

**Comment by jmcounters** [comment]
I tried removing all the container and the quorum-dev-quickstart directory altogether, still facing the same issue

**Comment by jmcounters** [comment]
Ran docker logs and found these in every restarting container

**Comment by jmcounters** [comment]
![image](https://user-images.githubusercontent.com/118317606/202917803-30251b96-0d27-4140-a86e-e566d07ea2b3.png)

**Comment by jmcounters** [comment]
Also tried logging in as root and remove and run the containers again, same issue. I hope someone can look into this soon. Thanks!

**Comment by jmcounters** [comment]
@joshuafernandes Would appreciate you input on this. Thanks

**Comment by joshuafernandes** [comment]
Hello @jmcounters 

What OS are you running this on? Could you also give us a run through of how you started things up please so we can replicate?

Thanks

**Comment by jmcounters** [comment]
Hi @joshuafernandes ,

Good day!!! Thanks for your response!

So here's what the environment is like.

1. Operating system - I have run into this constantly with no fail on Ubuntu 18.04, 20.04, 22.04
2. Docker Engine - 20.10.21
3. Docker Compose - 2.12.2. This came with the Docker Engine installation. I use it with Docker Compose-switch, a tool to run docker compose commands in v1.x accepted commands. Quorum quickstart uses commands only accepted by docker-compose v1.x (i.e. "docker-compose -f docker-compose-deps.yml stop"), which wouldn't run on v2.x because to call docker-compose, you should use "docker compose" not "docker-compose"
4. Quorum Quickstart options:
- Ethereum Client - GoQuorum
- Codefi Orchestrate - N
- Quorum Key Manager - N
- Private transactions - Y
- Loki
- Default directory (./quorum-test-network)


If it is worth noting, here's what the setup before I started running into the container issue. The only difference is the private transactions switch since I need tessera  nodes on this setup and I did not know at the time that I need to say Yes to that. After discovering that, I get the issue already.

1. Operating system - Ubuntu 20.04
2. Docker Engine - 20.10.21
3. Docker Compose - 2.12.2 with the docker engine installation and used compose-switch too
4. Quorum Quickstart options:
- Ethereum Client - GoQuorum
- Codefi Orchestrate - N
- Quorum Key Manager - N
- **Private transactions - N**
- Loki
- Default directory (./quorum-test-network)


Let me know what to check. I would love to learn how to troubleshoot this an I am new here.

Thanks!

**Comment by joshuafernandes** [comment]
Hello @jmcounters Thankyou for that. I wouldn't go back as far as Ubuntu 18.04, but the quickstart should work fine on ubuntu 20.04 or 22.04

I've personally got my machine running on 22.04 natively. Are you running WSL with Ubuntu by any chance? Out of curiosity what are your hardware resources like (specifically RAM)

You can check why the containers are dying with 

```docker ps -a ```

Then 

```docker logs  quorum-test-network-validator3-1``` Replace the name of the container to match whatever shows up. From the look of it, there appear to be file system permission errors.

**Comment by jmcounters** [comment]
It doesn't say anything related to why it's starting with the docker ps -a. For the logs, here's the result as shared previously where I used the container ID instead
![image](https://user-images.githubusercontent.com/118317606/203486670-4077a2f0-8a7f-406e-8a16-86068af924cf.png)

I'm running the Ubuntu servers on azure and not using WSL. I tried WSL on my local windows machine but I don't think windows 11 is properly supported.

Any direction we should look into? Regarding permission, I'm running the scripts with SUDO so I'm not sure what could go wrong.

**Comment by jmcounters** [comment]
Hi @joshuafernandes,

I did try this setup

**Comment by joshuafernandes** [comment]
Hi @jmcounters that is really very odd. 

I'll be back online in around 7 hours, Im on AEST at present. This might work for you in the interim? https://azuremarketplace.microsoft.com/en-us/marketplace/apps/consensys.quorum-dev-quickstart?tab=overview was published a wee while ago but I think will have enough to get you going?

Cheers

**Comment by joshuafernandes** [comment]
> Hi @joshuafernandes,
> 
> I did try this setup using WSL on my Windows 11 machine and still got the same issue.
> 
> * npx quorum-dev-quickstart@0.0.77
> * clean Ubuntu 22.04, running as the ubuntu user
> * docker version Client: Docker Engine - Community, Version: 20.10.21
> * nodejs 18
> * docker-compose version 1.29.2
> 
> I must be doing something awfully wrong for me to end up with failing containers every single time. Maybe something's wrong with the images I am pulling? I'm not sure.
> 
> Are you on the ConsenSys discord? I am available in the next 16 hours. Would it be possible for us to chat over there so I you can look into how I do things? It's really important for me to move forward with this. My username is johndc and I've posted about this as well on the [#quorum-general ](https://discord.com/channels/697535391594446898/722244032407011359) thread :(

On Windows 11 with WSL2 you can do this a couple of ways:
1. Install WSL2 & docker desktop (set this up so the it uses the wsl2 based engine per https://docs.docker.com/desktop/windows/wsl/)
2. Give it enough memory & cpu - think about 8-12G ram would do well
3. Start a terminal session in WSL2 which I think already has nodejs - if not install there
4. Run `docker ps` to make sure this works
5. Then run `npx quorum-dev-quickstart@0.0.77` and should work fine

Second approach is to skip docker desktop (I prefer this myself)
1. Install WSL2 and docker (& compose) and nodejs as normal for Ubuntu - once done you may need to restart
2. Start a fresh terminal session of WSL2
3. `sudo service docker start` which will start docker up for you
4. Repeat steps 4 &5 from above 

Regardless of option the networking works just fine and I could browse grafana & the explorer on chrome/firefox on the Windows host

**Comment by joshuafernandes** [comment]
> > Hi @joshuafernandes,
> > I did try this setup using WSL on my Windows 11 machine and still got the same issue.
> > 
> > * npx quorum-dev-quickstart@0.0.77
> > * clean Ubuntu 22.04, running as the ubuntu user
> > * docker version Client: Docker Engine - Community, Version: 20.10.21
> > * nodejs 18
> > * docker-compose version 1.29.2
> > 
> > I must be doing something awfully wrong for me to end up with failing containers every single time. Maybe something's wrong with the images I am pulling? I'm not sure.
> > Are you on the ConsenSys discord? I am available in the next 16 hours. Would it be possible for us to chat over there so I you can look into how I do things? It's really important for me to move forward with this. My username is johndc and I've posted about this as well on the [#quorum-general ](https://discord.com/channels/697535391594446898/722244032407011359) thread :(
> 
> On Windows 11 with WSL2 you can do this a couple of ways:
> 
> 1. Install WSL2 & docker desktop (set this up so the it uses the wsl2 based engine per https://docs.docker.com/desktop/windows/wsl/)
> 2. Give it enough memory & cpu - think about 8-12G ram would do well
> 3. Start a terminal session in WSL2 which I think already has nodejs - if not install there
> 4. Run `docker ps` to make sure this works
> 5. Then run `npx quorum-dev-quickstart@0.0.77` and should work fine
> 
> Second approach is to skip docker desktop (I prefer this myself)
> 
> 1. Install WSL2 and docker (& compose) and nodejs as normal for Ubuntu - once done you may need to restart
> 2. Start a fresh terminal session of WSL2
> 3. `sudo service docker start` which will start docker up for you
> 4. Repeat steps 4 &5 from above
> 
> Regardless of option the networking works just fine and I could browse grafana & the explorer on chrome/firefox on the Windows host

One thing I'll add here is that you must run the npx command in the context of the WSL2 shell - it won't work if you did this on the windows drive first via powershell (anywhere on /mnt/c/... will fail)

**Comment by joshuafernandes** [comment]
On Azure using the Marketplace offering with default settings https://azuremarketplace.microsoft.com/en-us/marketplace/apps/consensys.quorum-dev-quickstart?tab=overview

This runs on ubuntu 18.04 from the look of it and the setup of the vm lives at ```/var/lib/waagent/custom-script/download/0# cat qdq-setup.sh ```

![image](https://user-images.githubusercontent.com/3722503/203650793-b06fce5b-6bd0-47ea-8481-3d7b719e88c8.png)

![image](https://user-images.githubusercontent.com/3722503/203650827-c10ea0bd-a8fe-4c33-9edd-5e0def4e7e6a.png)

you get the idea, lots more building...
![image](https://user-images.githubusercontent.com/3722503/203650887-9b337666-e34e-4ee3-878f-7b93fbefb77d.png)

and then locally use the VM's IP
![image](https://user-images.githubusercontent.com/3722503/203651501-9e08e350-5db4-40af-bce3-6b387bf380c9.png)

![image](https://user-images.githubusercontent.com/3722503/203651575-f044c05a-ae53-4b8d-a6d2-dda122bae111.png)

**Comment by jmcounters** [comment]
Hi @joshuafernandes 

I still pursued working on my WSL2 Ubuntu on Windows 11. Had to reset to start fresh after upping the memory. Same issue. Here's the result of `top`

![image](https://user-images.githubusercontent.com/118317606/203679112-6ba52d4b-6f63-45d8-8c28-4cd94e422843.png)

How do we go about inspecting why these containers won't start?

While waiting for your response, I will try Quickstart on Azure and will let you know.

**Comment by joshuafernandes** [comment]
> Hi @joshuafernandes
> 
> I still pursued working on my WSL2 Ubuntu on Windows 11. Had to reset to start fresh after upping the memory. Same issue. Here's the result of `top`
> 
> ![image](https://user-images.githubusercontent.com/118317606/203679112-6ba52d4b-6f63-45d8-8c28-4cd94e422843.png)
> 
> How do we go about inspecting why these containers won't start?
> 
> While waiting for your response, I will try Quickstart on Azure and will let you know.

Aye, thats very odd indeed. The problem is being able to reproduce this and I can't seem to get it to do that. What have you got for RAM at present on docker in WSL2? The only thing to do is to check the logs and see why the containers fail, but short of that there's little more that can be done. Let us know how you go with the VM on Azure.

An alternative to this is to run the binaries by hand and you could try scripting that - similar to what we do with the compose? https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-qbft-network/

**Comment by jmcounters** [comment]
Hi @joshuafernandes,

Azure template worked for me! I'm only on free azure subscription so I'd like to know what's the best way to shut these services down so I can return from it perfectly fine. Currently, aside from the quickstart, I have installed Cakeshop as it is required of me to setup.

Thank you!

**Comment by joshuafernandes** [comment]
Hi @jmcounters 

Good to hear!

Check the file on the VM at `/var/lib/waagent/custom-script/download/0# cat qdq-setup.sh` - that is all you need to get up and going on a linux host. The quickstart is designed to _just_ start and run be it Windows, OSX or Linux.

I'd imagine you need to shut the VM down to save on cost, you may still pay for things like an IP but that'd be minimal. When you have this working fine locally, you can delete the Azure resource group altogether.

Cheers
