### ISSUE TITLE
Log is not created for quorum node

### ISSUE THREAD

**Issue by Shweta-hlf** [ConsenSys/quorum-dev-quickstart#224]
![quorum3Screen](https://user-images.githubusercontent.com/60926287/208122193-9eab265c-bead-44ab-9ace-9c3a8dfa9c3e.JPG)
Hi Team,
I am trying to create goquorum network using quorum-dev-quickstart.I am using below command.
./network.sh up

But getting following issues.

1. Log is not created for quorum node in /log/quorum directory.
2. Tessara node is started in unhealthy status.

Kindly help out.

Regards!!
![quorum1Screen](https://user-images.githubusercontent.com/60926287/208115634-2c8409d6-d5dc-4eb5-b07e-93efc8724f08.JPG)
![quorum2Screen](https://user-images.githubusercontent.com/60926287/208115664-27f29319-d240-47eb-9f09-ae474268adb2.JPG)

**Comment by m0kr** [comment]
Hi Shweta,

 I have tried with Ubuntu 18.04 OS and its working fine for me. So my question from the ConsenSys team, do you have recommendation for operating system where this setup works properly?

**Comment by joshuafernandes** [comment]
Hi @Shweta-hlf There are several containers that have exited in your screenshots and can't tell why. What version of the quickstart are you using and what are you system specs please?

@m0kr the quickstart works regardless of OS and targets MacOS, Linux, and Windows (with WSL2). Any OS of choice is fine per the user, however recommend that the specs of the machine allow the many containers to run depending on client of choice.
