### ISSUE TITLE
Tessera member are started in unhealthy status

### ISSUE THREAD

**Issue by Shweta-hlf** [ConsenSys/quorum-dev-quickstart#226]
Hi Team,

I am using ubuntu 18.04 ,docker (Docker version 20.10.22),docker-compose(Docker Compose version v2.12.0) but tessera members are not started in healty status.

Kindly look into the issue and reply asap
[quickdeverror.txt](https://github.com/ConsenSys/quorum-dev-quickstart/files/10287507/quickdeverror.txt)

**Comment by joshuafernandes** [comment]
Refer to #227
