### ISSUE TITLE
Getting error while running Tessera using quorum-dev-quickstart...................Error Code: 42102???

### ISSUE THREAD

**Issue by m0kr** [ConsenSys/quorum-dev-quickstart#227]
I am running ./run.sh and all container are running with healthy status but Tessera is not running and getting below error in log file:

Please help me to resolve this issue!!!
/quorum-test-network-up/network/logs/tessera ---

{"timestamp":"2022-12-22 14:30:33,130","container":"01f2023e1ab9","level":"WARN","thread":"main","class":"e.l.all","logger":"eclipselink.logging.all","message":"Exception [EclipseLink-4002] (Eclipse Persistence Services - 3.0.2.v202107160933): org.eclipse.persistence.exceptions.DatabaseExceptionInternal Exception: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ST_AFFECTED_TRANSACTION" not found; SQL statement:ALTER TABLE ST_AFFECTED_TRANSACTION DROP CONSTRAINT FK_ST_AFFECTED_TRANSACTION_TXN_ID [42102-212]Error Code: 42102Call: ALTER TABLE ST_AFFECTED_TRANSACTION DROP CONSTRAINT FK_ST_AFFECTED_TRANSACTION_TXN_IDQuery: DataModifyQuery(sql="ALTER TABLE ST_AFFECTED_TRANSACTION DROP CONSTRAINT FK_ST_AFFECTED_TRANSACTION_TXN_ID")","throwable":""}

**Comment by joshuafernandes** [comment]
Hello @m0kr what version of the quickstart are you using please? The discord channels are better for this https://discord.com/channels/697535391594446898/905421497416433704

**Comment by joshuafernandes** [comment]
Have tried the lastest version on Windows + WSL2

![image](https://user-images.githubusercontent.com/3722503/212900112-e269aa8a-8f03-42d0-ac62-7906b4449b83.png)

Same for the logs:

![image](https://user-images.githubusercontent.com/3722503/212900437-e62d6965-a313-4693-bbd2-00328a40b503.png)

@m0kr what options did you select please and what is your system environment like? We can try and reproduce this issue to figure out what is going on
