### ISSUE TITLE
Requires Docker compose

### ISSUE THREAD

**Issue by cauta** [ConsenSys/quorum-dev-quickstart#231]
I have installed quorum-dev-quickstart with the following script.
```
quorum-dev-quickstart --clientType=goquorum --privacy=false --orchestrate=false --blockscout=true --monitoring=default --outputPath='./quorum-test-network' 
```

But i run ./run.sh
it showed me 
```
This script requires Docker compose but it's not installed.
Refer to documentation to fulfill requirements.
```

i have installed the docker-compose too
Check the .common.sh i saw that the script with docker-compose missing the 'dash'
<img width="585" alt="image" src="https://user-images.githubusercontent.com/15400058/212795080-4a50bb4e-3abf-4260-b39d-36d54f3ad7c1.png">

it also missing in the rest bash file

My environment is: Macbook pro 13 inch 2020 Apple sillicon M1, MacOS v12.3

**Comment by cauta** [comment]
Update:
the same error happen in Ubuntu 18.04.6 LTS

**Comment by joshuafernandes** [comment]
What version of compose do you have? We've upgraded to docker compose v2 which is installed as a [plugin now ](https://docs.docker.com/compose/install/linux/#install-using-the-repository) 
![image](https://user-images.githubusercontent.com/3722503/212798343-e6628cb9-5193-4243-bfe2-f552f6fa643f.png)

Ubuntu 18 reached EOL in 2 months, strongly recommend 22.04 or if you need to use legacy 20.04
