### ISSUE TITLE
ChainId in genesis.json does not match with RPC net_version

### ISSUE THREAD

**Issue by cauta** [ConsenSys/quorum-dev-quickstart#238]
This error happen when we change the chainId in genesis file.
RPC net_version always return id: 1337
RPC eth_chainId return by genesis

impact:
Metamask wallet receive eth_chainId
Truffle receive from net_version
Truffle will throw migrate error:
```
Error: The network id specified in the truffle config (1338) does not match the one returned by the network (1337).  Ensure that both the network and the provider are properly configured.
```

Solution:
In quorum-dev-quickstart/files/goquorum/config/goquorum/docker-entrypoint.sh
Update new line after GENESIS_FILE to update Quorum network id when execute command
```
QUORUM_NETWORK_ID=$(grep -o '"chainId": *[0-9]*' $GENESIS_FILE | grep -o '[0-9]*$')
```

**Comment by joshuafernandes** [comment]
Hello @cauta this is left for the user to customize, we cannot implement this because it affects both clients, ie we build goq like this but besu just uses a genesis file as a volume. 

I'd suggest forking this repo and customizing to suit your needs
