### ISSUE TITLE
HttpResponseError : socket hang up

### ISSUE THREAD

**Issue by lyrWinterCat** [ConsenSys/quorum-dev-quickstart#239]
hi, I'm glad to meet your code, and I need some help of error....
I'm use Macbook M1 Pro , npm 9.4.0 v , docker 20.10.22 v.
I followed all steps of Usage, and I need some help of Orchestrate.
I finished of Environment setup , and I can't follow tutorial of Register-Chain.

`
> codefi-orchestrate-quick-start@4.0.0 register-chain
> dotenv ts-node src/register-chain

HttpResponseError: Error: socket hang up
    at Function.parseErrResponse (/Users/wm-il000516/quorum-test-network/node_modules/pegasys-orchestrate/lib/client/HttpClient.js:98:20)
    at HttpClient.<anonymous> (/Users/wm-il000516/quorum-test-network/node_modules/pegasys-orchestrate/lib/client/HttpClient.js:46:34)
    at Generator.throw (<anonymous>)
    at rejected (/Users/wm-il000516/quorum-test-network/node_modules/pegasys-orchestrate/lib/client/HttpClient.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  isHttpError: true,
  status: 500,
  headers: {
    url: '/chains',
    method: 'post',
    data: '{"name":"dev","urls":["http://rpcnode:8546"]}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Bearer [TENANT_AUTH_TOKEN]',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 45
    },
    baseURL: 'http://localhost:8031',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  data: undefined
}
`
Could you let me know if there are any settings I'm missing?
Or Do you have any idea how i can solve this problem?

**Comment by joshuafernandes** [comment]
Hi @lyrWinterCat thankyou for raising this. I'd suggest raising this issue in the https://github.com/ConsenSys/orchestrate and you should be able to assistance from that team faster
