### ISSUE TITLE
Array format in node-explorer

### ISSUE THREAD

**Issue by Atrass23** [ConsenSys/quorum-dev-quickstart#242]
I'm trying to use a custom contract in the contracts section of the node-explorer, and i'm having issues using an array of addresses as an input parameter of a function. 
Actually i've tryed to insert it using square brakets (i.e [0x..., 0x...], also with quotes/single quotes ["0x..."], ['0x...']) and also without brackets using quotes of any kind and tryed also without quotes or without brackets, but i'm always getting the error that the input format is wrong.
i.e. of an error: Error encoding arguments: Error: expected array value (argument=null, value="0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2", code=INVALID_ARGUMENT, version=abi/5.5.0).
What i'm missing?
Sorry if the question might be trivial but really i can't figure it out.
Thank you.

**Comment by joshuafernandes** [comment]
Hi @Atrass23 
Could you please give us a set of reproducible steps so that we can look into this?

Cheers

**Comment by Atrass23** [comment]
Hi @joshuafernandes
i'm using a smart contract in which there is a simple function like this:  function setStore(address[] memory _address) public{
        for(uint i=0; i<_address.length; i++){
          store.push(_address[i]);
        }
      }
when interacting with the GUI, inserting the array elements like this: 
![image](https://user-images.githubusercontent.com/82364772/219981579-997e3b7a-43d0-47bb-b67e-8745c93171e0.png)
leads to the error described before.
also trying without [ ], "" or ' ' (I tried all the possible combinations).
So the problem is that i'm not finding a way to insert an array in the function input in the GUI.

**Comment by NickSneo** [comment]
Hey @Atrass23 ,

I have used your smart contract function - 

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

contract Test {
    address[] store;
    function setStore(address[] memory _address) public{
        for(uint i=0; i<_address.length; i++){
            store.push(_address[i]);
        }
    }
}
```

Testing on Remix IDE, and it seems working fine for me with input - `["0x5B38Da6a701c568545dCfcB03FcB875f56beddC4","0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2"]`

Can you please test, if it is working fine?

**Comment by joshuafernandes** [comment]
Hello @Atrass23 

Also confirm no issue with it, we even have a contract built in that does read/writes of arrays 

![image](https://github.com/ConsenSys/quorum-dev-quickstart/assets/3722503/1f9fda8c-b321-4aa6-953a-8e696ffd2b75)

Unfortunately can't sort this one out without being able to reproduce it
