### ISSUE TITLE
metamask won't register custom erc20 token 

### ISSUE THREAD

**Issue by torestin** [ConsenSys/quorum-dev-quickstart#249]
Hi there, i am probably missing something simple. So I made a pretty standard erc20 on the quorum-dev-quickstart example. Interacting with the contract works fine, but the token itself won't show up on metamask. (and I deployed the same contract on goerli, it showed up just fine) Any idea why this is?

**Comment by joshuafernandes** [comment]
Not quite sure, what version of Metamask is this - you need to set MM to use the custom RPC url is about the only thing I can think of, but might be a good thing to get a steps of how to reproduce this and post as an issue to https://github.com/MetaMask
