### ISSUE TITLE
Unable to add new nodes as in the Quorum Developer Quickstart.

### ISSUE THREAD

**Issue by focpan** [Consensys/quorum-dev-quickstart#262]
### Hi, I am new to quorum and I'm trying to quorum，when following the “add new node” steps in the quickstart guide, I am unable to join the new node, and the blockchain explorer still only displays the original eight nodes.
![image](https://github.com/Consensys/quorum/assets/46263854/04a3ca24-2721-404a-b14e-765a90f263a9)

**The containers related to the newnode have been successfully started, but there is an authentication error issue.**

> INFO [07-17|03:51:55.007] QBFT: initialize new round               address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1017 target.round=0 lastProposal.number=1017 lastProposal.hash=6d0fbd..0aa271
INFO [07-17|03:52:00.506] QBFT: handle final committed             address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1018 state="Accept request"
INFO [07-17|03:52:00.506] QBFT: initialize new round               address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1018 target.round=0 lastProposal.number=1018 lastProposal.hash=5f9e18..0a14ac
INFO [07-17|03:52:05.006] QBFT: handle final committed             address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1019 state="Accept request"
INFO [07-17|03:52:05.006] QBFT: initialize new round               address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1019 target.round=0 lastProposal.number=1019 lastProposal.hash=969c06..de97ab
INFO [07-17|03:52:10.008] QBFT: handle final committed             address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1020 state="Accept request"
INFO [07-17|03:52:10.008] QBFT: initialize new round               address=0xa16C7e6F5ea55064e3EDfebEe29B8e1894315bff current.round=0 current.sequence=1020 target.round=0 lastProposal.number=1020 lastProposal.hash=713ca9..c7a025
WARN [07-17|03:52:10.008] Block sealing failed                     err=unauthorized

**My key created by  ./extra/generate_node_details.js  ,because I can‘t find generate_node_keys.js like the quickstart guide，and I add its content to static nodes file and permissions file**

> [
"enode://6485f1adb3f11fa17f5162ab39e4e8136c1e46f751ba17f7a9493f12a512ba91bd97598596d2630c595c8cbd7b4fd1a329085a3a2418e2a01480447e09ebe43d@172.16.239.41:30303?discport=0&raftport=53000"
]

My  setting of  docker-compose.yaml is copyed from quickstart guide

>  newnode:
    << : *quorum-def
    container_name: newnode
    ports:
      - 18545:8545/tcp
      - 18546:8546/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_GENESIS_MODE=standard
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/newnode:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.41

**Does this error have any relation to key generation?**
System version ：Windows11, 5.15.90.1-microsoft-standard-WSL2，Ubuntu 18.04

**Comment by joshuafernandes** [comment]
Hello @focpan 

Few things I'd suggest based on the above:
1. WSL2 works fine (am using it myself) - Suggest using 22.04 or at minimum 20.04. 18.04 has reached end of life
2. The `extra` folder is at the root level. Adjust the path to where you run the command from. The file is here `https://github.com/Consensys/quorum-dev-quickstart/tree/master/files/common/extra`
3. Follow the remainder of the steps here https://docs.goquorum.consensys.net/tutorials/quorum-dev-quickstart/using-the-quickstart#add-a-new-node-to-the-network
4. The quorum explorer uses a static list of nodes to connect to - it isn't dynamic. [Docs](https://github.com/Consensys/quorum-explorer). Edit the config.json file that is passed to the explorer as a volume with your new node's details ` - ./quorum-explorer/config.json:/app/config.json`
