### ISSUE TITLE
Hyperledger Besu block explorer unable to deploy sample contract

### ISSUE THREAD

**Issue by leeronkit** [Consensys/quorum-dev-quickstart#263]
Hi, I am following current latest guide on Hyperledger Besu
https://besu.hyperledger.org/stable/private-networks/tutorials/quickstart#deploy-your-own-dapp

Able to bring up everything until contract deploying. Was facing this error when deploying
![image](https://github.com/Consensys/quorum-dev-quickstart/assets/25733356/8c95fbd6-6b3e-45a6-b74f-13ade6600360)

Already set the network in Metamask
![image](https://github.com/Consensys/quorum-dev-quickstart/assets/25733356/a303a7d0-84ed-43e9-bd15-b11d51ce4773)

Running on VM in AWS. Attached RPC url is the VM IP address.
Anyone have idea? Thanks

**Comment by joshuafernandes** [comment]
Hello @leeronkit 

Can you make RPC calls directly to that endpoint? If so the endpoint & explorer are working fine and you need to raise this in Metamask as an issue.

Cheers

**Comment by leeronkit94** [comment]
Hi @joshuafernandes 

Yes I am able to make RPC directly to the endpoint and able to get responses
![image](https://github.com/Consensys/quorum-dev-quickstart/assets/138543071/25c6ce4e-b6e0-496e-8eeb-e671fdbf7076)

**Comment by joshuafernandes** [comment]
Hi @leeronkit , thanks for confirming. This needs to be opened as an issue for MM then, there is no reason Im aware of that would throw that error
