### ISSUE TITLE
Anyway to upgrade latest geth in container?

### ISSUE THREAD

**Issue by cauta** [Consensys/quorum-dev-quickstart#272]
hi, is there anyway to quickly run or upgrade new version of geth in container by quorum-dev-quickstart?

**Comment by joshuafernandes** [comment]
Hello @cauta we are using the latest release of goquorum in the containers https://github.com/Consensys/quorum-dev-quickstart/blob/master/files/common/.env#L5.

GoQ releases are here: https://github.com/ConsenSys/quorum/releases
