### ISSUE TITLE
Warning message on npx script

### ISSUE THREAD

**Issue by mauriciotp** [Consensys/quorum-dev-quickstart#279]
I'm getting this warning message when trying to run a besu network through `npx quorum-dev-quickstart`:

![image](https://github.com/Consensys/quorum-dev-quickstart/assets/82242064/ec65de0e-a04f-4b95-9f0e-72c8cdbfbccb)

Thus, with this warning i can't deploy the network.

Any idea on how to solve it?

**Comment by joshuafernandes** [comment]
Hello @mauriciotp 
This means you have already pre created that docker network

Run `docker network ls` and see what created it, and you may need to remove the old one with `docker network rm quorum-dev-quickstart` https://docs.docker.com/engine/reference/commandline/network_rm/

Cheers

**Comment by mauriciotp** [comment]
Thanks @joshuafernandes! Solved!
