### ISSUE TITLE
`remove.sh` prunes all images from Docker

### ISSUE THREAD

**Issue by ricardolyn** [ConsenSys/quorum-dev-quickstart#43]
Taking into consideration the limitations introduced by Docker when pulling images, we shouldn't remove the images from Docker when we run `./remove.sh`. Doing this will lead to continuos pulls from the docker repository which could hit the daily limit for that IP quickly (and also makes another `run.sh` slower for the same image tags).

This should be an optional parameter like `--prune` to that script.

**Comment by joshuafernandes** [comment]
Hi @ricardolyn 

Thanks for raising this; its a very valid point and should be fixed with #47 

Cheers
Josh
