### ISSUE TITLE
Wrong chainId

### ISSUE THREAD

**Issue by bcuestav** [ConsenSys/quorum-dev-quickstart#51]
Related with issue #48, the EventEmitter example  keeps crashing because chainId is 2018 in the next scripts:

https://github.com/ConsenSys/quorum-dev-quickstart/blob/2f16d92c5dfbb2ff16bd3f6665bb995cdebfcc19/files/besu/smart_contracts/scripts/deploy.js#L8

https://github.com/ConsenSys/quorum-dev-quickstart/blob/b06c0ba71cbc2fb14afe10523cbdc641e551bb8b/templates/gquorum/docker-compose.yml#L221

https://github.com/ConsenSys/quorum-dev-quickstart/blob/3230f2c2c5aaf0333a68a35778dba59b15be303b/templates/besu/docker-compose.yml#L140

I try send a pull request but I dont have permissions.

**Comment by joshuafernandes** [comment]
Hi @bcuestav, 
Thank you for raising this. This should be sorted with #57 & #49 

Cheers
