### ISSUE TITLE
How to customize the Dapp deployment

### ISSUE THREAD

**Issue by mohjam2004** [ConsenSys/quorum-dev-quickstart#53]
can I run the dapp provided in quorum-dev-quickstart in my deployed besu network? If yes, what changes I must do to run this dapp in my deployed besu network? I don't want to run it in "quorum-dev-quickstar" deployed network. I have my own deployed besu network
I mean what changes I must do in these Dapp configuration file?
![image](https://user-images.githubusercontent.com/59224403/115109699-a193fc00-9f8c-11eb-88b0-d927d5d6a19d.png)

**Comment by joshuafernandes** [comment]
The DApp in this repo is the Truffle Pet-Shop - full detail and tutorial is here https://www.trufflesuite.com:8443/tutorial 

Yes, it can be run on any network, it's not specific to this one. You need an account on the chain with eth in it (and a keyProvider) and an RPC endpoint. For reference this is one way of several to do it https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/common/dapps/pet-shop/custom_config/truffle-config.js

**Comment by mohjam2004** [comment]
Hello @joshuafernandes 
This URL is not available: https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/common/dapps/pet-shop/custom_config/truffle-config.js

**Comment by mohjam2004** [comment]
I have found it:
https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/files/besu/dapps/pet-shop/custom_config/truffle-config.js
