### ISSUE TITLE
Installation failed. Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Duanraudon** [ConsenSys/quorum-dev-quickstart#66]
❌ Installation failed. Error: ENOENT: no such file or directory, mkdir '/project/quorum-test-network/block-explorer-light/dist
/css'
![image](https://user-images.githubusercontent.com/34836995/119302992-96bd3d00-bc97-11eb-8e07-e7a6411ef4c4.png)

**Comment by joshuafernandes** [comment]
Hi @Duanraudon this generally happens for one of two reasons:
- the user running it doesn't have rights to create the folder 
- the folder already exists 

Im not able to reproduce this error, which version were you using of the quorum-dev-quickstart? What OS/environment is this on?

This is what I see below
![image](https://user-images.githubusercontent.com/3722503/121610628-cd69c480-ca99-11eb-8e22-23e923b3c519.png)
