### ISSUE TITLE
Cakeshop version is not latest (Update to 0.12.1)

### ISSUE THREAD

**Issue by ShantnuS** [ConsenSys/quorum-dev-quickstart#74]
The version of cakeshop used in this quickstart is 0.11.0. This is an old version that does not include the Cakeshop API page. Can this be updated to use 0.12.1?

**Comment by vmichalik** [comment]
Hey @ShantnuS, I'm sorry for the super late reply to you about this - I'll take a look, see if we can get it updated. If you are able to make a PR for it sooner than I do, please go for it!

**Comment by joshuafernandes** [comment]
@ShantnuS this is fixed in v 0.0.28, as @vmichalik said we are more than happy for community members to send PRs across
