### ISSUE TITLE
Docker-compose file is broken

### ISSUE THREAD

**Issue by BravoNatalie** [ConsenSys/quorum-dev-quickstart#81]
I'm trying to set up ConsenSys Quorum using Hyperledger Besu for the first time, and I run into an error on the docker-compose file while following the quickstart [tutorial](https://consensys.net/quorum/products/guides/getting-started-with-consensys-quorum/).

I follow the following steps to generate the error:

 1. `npx quorum-dev-quickstart`

 2. Which Ethereum client would you like to run? Default: (1) **My answer: 1**
	1. Hyperledger Besu
	2. GoQuorum

 3. Do you want to try out Codefi Orchestrate? Note: choosing yes will direct you to a login/registration page. [Y/n] **My answer: n**

 4. Do you wish to enable support for private transactions? [Y/n] **My answer: y**

 5. Do you wish to enable support for logging with Splunk or ELK (Elasticsearch, Logstash & Kibana)? Default: (1) **My answer: 3**
	1. None
	2. Splunk
	3. ELK

 6. Where should we create the config files for this network? Please
choose either an empty directory, or a path to a new directory that does not yet exist. Default: ./quorum-test-network
**./quorum-test-network**

 7. ✅ Installation complete.
To start your test network, run 'run.sh' in the directory, './quorum-test-network'

 8. `cd quorum-test-network`

 9. `./run.sh`

Error on terminal:

    *************************************
    Quorum Dev Quickstart
    *************************************
    Start network
    --------------------
    Starting network...
    ERROR: yaml.constructor.ConstructorError: while constructing a mapping
      in "./docker-compose.yml", line 383, column 5
    expected a mapping or list of mappings for merging, but found scalar
      in "./docker-compose.yml", line 253, column 19
    ERROR: yaml.constructor.ConstructorError: while constructing a mapping
      in "./docker-compose.yml", line 383, column 5
    expected a mapping or list of mappings for merging, but found scalar
      in "./docker-compose.yml", line 253, column 19
    *************************************
    Quorum Dev Quickstart 
    *************************************
    ----------------------------------
    List endpoints and services
    ----------------------------------
    JSON-RPC HTTP service endpoint                 : http://localhost:8545
    JSON-RPC WebSocket service endpoint            : ws://localhost:8546
    Web block explorer address                     : http://localhost:25000/

Some information about my environment:

```
$  uname -a                
Linux bravo-K46CB 5.4.0-77-generic #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ docker --version        
Docker version 20.10.7, build f0df350

$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

**Comment by joshuafernandes** [comment]
Hello @BravoNatalie 

Thank you for reporting this, it should be fixes with #82. Could you try this again please and let us know if there is still an issue?

Cheers
Josh

**Comment by BravoNatalie** [comment]
Hi @joshuafernandes, 

Thanks for the quick response. I just ran it again and it has the same error.

**Comment by joshuafernandes** [comment]
Hi @BravoNatalie 

This is very odd, those lines shouldn't exist in code anymore. Could you double check the version please? 

I'm running on Ubuntu 20.04 and this is what I get on version 0.0.26:

![image](https://user-images.githubusercontent.com/3722503/124842823-d0da6800-dfd3-11eb-937b-5e77bcc23cb4.png)
![image](https://user-images.githubusercontent.com/3722503/124842846-de8fed80-dfd3-11eb-8aa9-8d5d13f6c585.png)

I've just released 0.0.27 which keeps the besu env vars in one place and the code is a bit easier to follow
and this is what I get:
![image](https://user-images.githubusercontent.com/3722503/124843314-07fd4900-dfd5-11eb-93fe-30310296ba49.png)
![image](https://user-images.githubusercontent.com/3722503/124843465-51e62f00-dfd5-11eb-8d68-bdecf9b04f72.png)

Cheers
Josh

**Comment by chriszertamayo** [comment]
this is what i got in monterey mac why is it not working? please help

<img width="807" alt="Screen Shot 2023-03-17 at 12 42 59 AM" src="https://user-images.githubusercontent.com/53213111/225691703-6428669f-1c4c-4587-8de2-6d8697f93f68.png">
<img width="808" alt="Screen Shot 2023-03-17 at 12 43 16 AM" src="https://user-images.githubusercontent.com/53213111/225691760-e717a4b5-3c6d-408f-ad70-ad17e4851afe.png">
<img width="807" alt="Screen Shot 2023-03-17 at 12 42 59 AM" src="https://user-images.githubusercontent.com/53213111/225691806-d901f98f-bdbd-4536-9172-e61da9d284d5.png">

**Comment by ous-ahm2000** [comment]
i cant access to services endpoints , im using docker on windows , did anyone face this problem?


----------------------------------
List endpoints and services
----------------------------------
JSON-RPC HTTP service endpoint                 : http://localhost:8545
JSON-RPC WebSocket service endpoint            : ws://localhost:8546
Web block explorer address                     : http://localhost:25000/
